// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABzmirmg7fxBoffqMq4UgCl0LrOi-gZRk',
    appId: '1:858287076413:web:d66b353861f60f6b166654',
    messagingSenderId: '858287076413',
    projectId: 'myflutterproject-faf9a',
    authDomain: 'myflutterproject-faf9a.firebaseapp.com',
    storageBucket: 'myflutterproject-faf9a.appspot.com',
    measurementId: 'G-5WCHDQEN0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyn_Im1XHZGrI3zULJkHil2LKdKy_8CRg',
    appId: '1:858287076413:android:9c874b16f91b05e1166654',
    messagingSenderId: '858287076413',
    projectId: 'myflutterproject-faf9a',
    storageBucket: 'myflutterproject-faf9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl0LW-nQIqjwCRQky7uWuKcbWlCBRAZfQ',
    appId: '1:858287076413:ios:3ba14f96a7917bac166654',
    messagingSenderId: '858287076413',
    projectId: 'myflutterproject-faf9a',
    storageBucket: 'myflutterproject-faf9a.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl0LW-nQIqjwCRQky7uWuKcbWlCBRAZfQ',
    appId: '1:858287076413:ios:aab2ffa79fbbc5bc166654',
    messagingSenderId: '858287076413',
    projectId: 'myflutterproject-faf9a',
    storageBucket: 'myflutterproject-faf9a.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
